export const definitions: Record<string, string> = {
  unlimited: "No restrictions or limits on usage",
  rpc: "Remote Procedure Call - a protocol for requesting a service",
  calls: "Requests made to execute specific functions",
  power: "Computational capability and processing strength",
  remote: "Operations performed from a distance",
  procedure: "A set of instructions or method to perform a task",
  scale: "Ability to grow and handle increased load",
  applications: "Software programs designed for specific purposes",
  throttling: "Intentional slowing down of processing speed",
  limits: "Restrictions on usage or capacity",
  no: "Absence of restrictions",
  your: "Belonging to or associated with the user",
  with: "Accompanied by or using",
  the: "Used to point to a specific item",
  documentation: "Written materials that explain how to use a product",
  start: "Begin a process or action",
  building: "Creating or developing something",
  today: "On the present day",
  features: "Special characteristics or capabilities",
  possibilities: "Potential outcomes or capabilities",
  experience: "Knowledge or skill gained through practice",
  freedom: "State of being unrestricted",
  infrastructure: "Basic framework and systems",
  robust: "Strong and effective",
  global: "Worldwide or universal",
  performance: "How well something functions",
  real: "Actually existing or happening",
  time: "Continuous progress of existence",
  lightning: "Extremely fast",
  fast: "Moving or operating quickly",
  api: "Application Programming Interface",
  access: "Ability to use or reach something",
};