// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://islunvdimwlskoeogpkp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlzbHVudmRpbXdsc2tvZW9ncGtwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU5ODg0NjYsImV4cCI6MjA1MTU2NDQ2Nn0.9cjKVp0TDvOQqKewvuGnIKcYFc5LcERQx4qdIPjq3aw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);